const preguntasYRespuestas = [
  {
    id: 0,
    pregunta: "¿Qué equipo gano la Copa Mundial del 2022?",
    opcion1: "Argentina",
    opcion2: "Brasil",
    opcion3: "Francia",
    opcion4: "España",
    respuestaCorrecta: "Argentina",
  },
  {
    id: 1,
    pregunta: "¿Cuál es la capital de Francia?",
    opcion1: "Londres",
    opcion2: "Madrid",
    opcion3: "París",
    opcion4: "Roma",
    respuestaCorrecta: "París",
  },
  {
    id: 2,
    pregunta: "¿Cuál es el planeta más cercano al sol?",
    opcion1: "Venus",
    opcion2: "Marte",
    opcion3: "Mercurio",
    opcion4: "Júpiter",
    respuestaCorrecta: "Mercurio",
  },
  {
    id: 3,
    pregunta: "¿Quién escribió 'Cien años de soledad'?",
    opcion1: "Gabriel García Márquez",
    opcion2: "Mario Vargas Llosa",
    opcion3: "Jorge Luis Borges",
    opcion4: "Julio Cortázar",
    respuestaCorrecta: "Gabriel García Márquez",
  },
  {
    id: 4,
    pregunta: "¿En qué año llegó el hombre a la luna?",
    opcion1: "1965",
    opcion2: "1969",
    opcion3: "1972",
    opcion4: "1968",
    respuestaCorrecta: "1969",
  },
  {
    id: 5,
    pregunta: "¿Cuál es el océano más grande del mundo?",
    opcion1: "Atlántico",
    opcion2: "Índico",
    opcion3: "Ártico",
    opcion4: "Pacífico",
    respuestaCorrecta: "Pacífico",
  },
  {
    id: 6,
    pregunta: "¿Cuál es el elemento químico con el símbolo 'O'?",
    opcion1: "Oxígeno",
    opcion2: "Oro",
    opcion3: "Osmio",
    opcion4: "Óxido",
    respuestaCorrecta: "Oxígeno",
  },
  {
    id: 7,
    pregunta: "¿Qué artista pintó la Mona Lisa?",
    opcion1: "Vincent van Gogh",
    opcion2: "Leonardo da Vinci",
    opcion3: "Pablo Picasso",
    opcion4: "Claude Monet",
    respuestaCorrecta: "Leonardo da Vinci",
  },
  {
    id: 8,
    pregunta: "¿Cuál es el idioma más hablado en el mundo?",
    opcion1: "Inglés",
    opcion2: "Chino Mandarín",
    opcion3: "Español",
    opcion4: "Hindú",
    respuestaCorrecta: "Chino Mandarín",
  },
  {
    id: 9,
    pregunta: "¿En qué continente se encuentra el desierto del Sahara?",
    opcion1: "Asia",
    opcion2: "América",
    opcion3: "África",
    opcion4: "Europa",
    respuestaCorrecta: "África",
  },
  {
    id: 10,
    pregunta: "¿Cuál es el número pi aproximado a dos decimales?",
    opcion1: "3.12",
    opcion2: "3.14",
    opcion3: "3.16",
    opcion4: "3.18",
    respuestaCorrecta: "3.14",
  },
  {
    id: 11,
    pregunta: "¿Cuál es el animal terrestre más rápido?",
    opcion1: "Guepardo",
    opcion2: "León",
    opcion3: "Tigre",
    opcion4: "Antílope",
    respuestaCorrecta: "Guepardo",
  },
  {
    id: 12,
    pregunta: "¿Cuál es el número atómico del helio?",
    opcion1: "1",
    opcion2: "2",
    opcion3: "3",
    opcion4: "4",
    respuestaCorrecta: "2",
  },
  {
    id: 13,
    pregunta: "¿Quién es el autor de 'Don Quijote de la Mancha'?",
    opcion1: "Miguel de Cervantes",
    opcion2: "Federico García Lorca",
    opcion3: "Luis de Góngora",
    opcion4: "Lope de Vega",
    respuestaCorrecta: "Miguel de Cervantes",
  },
  {
    id: 14,
    pregunta: "¿Qué país ganó la Copa Mundial de Fútbol en 2018?",
    opcion1: "Brasil",
    opcion2: "Alemania",
    opcion3: "Francia",
    opcion4: "Argentina",
    respuestaCorrecta: "Francia",
  },
  {
    id: 15,
    pregunta: "¿Cuál es la fórmula química del agua?",
    opcion1: "H2O",
    opcion2: "CO2",
    opcion3: "O2",
    opcion4: "H2SO4",
    respuestaCorrecta: "H2O",
  },
  {
    id: 16,
    pregunta: "¿En qué año comenzó la Primera Guerra Mundial?",
    opcion1: "1912",
    opcion2: "1914",
    opcion3: "1916",
    opcion4: "1918",
    respuestaCorrecta: "1914",
  },
  {
    id: 17,
    pregunta: "¿Cuál es el idioma oficial de Brasil?",
    opcion1: "Español",
    opcion2: "Portugués",
    opcion3: "Francés",
    opcion4: "Italiano",
    respuestaCorrecta: "Portugués",
  },
  {
    id: 18,
    pregunta: "¿Quién pintó el techo de la Capilla Sixtina?",
    opcion1: "Rafael",
    opcion2: "Miguel Ángel",
    opcion3: "Donatello",
    opcion4: "Leonardo da Vinci",
    respuestaCorrecta: "Miguel Ángel",
  },
  {
    id: 19,
    pregunta: "¿Cuál es la moneda oficial de Japón?",
    opcion1: "Yuan",
    opcion2: "Won",
    opcion3: "Yen",
    opcion4: "Dólar",
    respuestaCorrecta: "Yen",
  },
  {
    id: 20,
    pregunta:
      "¿Qué gas se encuentra en mayor proporción en la atmósfera terrestre?",
    opcion1: "Oxígeno",
    opcion2: "Hidrógeno",
    opcion3: "Nitrógeno",
    opcion4: "Dióxido de carbono",
    respuestaCorrecta: "Nitrógeno",
  },
  {
    id: 21,
    pregunta: "¿Cuál es el río más largo del mundo?",
    opcion1: "Amazonas",
    opcion2: "Nilo",
    opcion3: "Yangtsé",
    opcion4: "Misisipi",
    respuestaCorrecta: "Amazonas",
  },
  {
    id: 22,
    pregunta: "¿Qué elemento tiene el símbolo 'Fe' en la tabla periódica?",
    opcion1: "Fósforo",
    opcion2: "Hierro",
    opcion3: "Flúor",
    opcion4: "Francio",
    respuestaCorrecta: "Hierro",
  },
  {
    id: 23,
    pregunta: "¿En qué año cayó el muro de Berlín?",
    opcion1: "1987",
    opcion2: "1988",
    opcion3: "1989",
    opcion4: "1990",
    respuestaCorrecta: "1989",
  },
  {
    id: 24,
    pregunta: "¿Cuál es el país más grande del mundo por superficie?",
    opcion1: "Estados Unidos",
    opcion2: "China",
    opcion3: "Rusia",
    opcion4: "Canadá",
    respuestaCorrecta: "Rusia",
  },
  {
    id: 25,
    pregunta: "¿Quién compuso la Novena Sinfonía?",
    opcion1: "Johann Sebastian Bach",
    opcion2: "Ludwig van Beethoven",
    opcion3: "Wolfgang Amadeus Mozart",
    opcion4: "Franz Schubert",
    respuestaCorrecta: "Ludwig van Beethoven",
  },
  {
    id: 26,
    pregunta: "¿En qué continente se encuentra el monte Kilimanjaro?",
    opcion1: "Asia",
    opcion2: "África",
    opcion3: "América del Sur",
    opcion4: "Europa",
    respuestaCorrecta: "África",
  },
  {
    id: 27,
    pregunta: "¿Cuál es la capital de Australia?",
    opcion1: "Sídney",
    opcion2: "Melbourne",
    opcion3: "Canberra",
    opcion4: "Perth",
    respuestaCorrecta: "Canberra",
  },
  {
    id: 28,
    pregunta:
      "¿Qué inventor es conocido por la patente de la bombilla incandescente?",
    opcion1: "Nikola Tesla",
    opcion2: "Alexander Graham Bell",
    opcion3: "Thomas Edison",
    opcion4: "George Westinghouse",
    respuestaCorrecta: "Thomas Edison",
  },
  {
    id: 29,
    pregunta: "¿Cuál es la distancia media de la Tierra al Sol?",
    opcion1: "150,000 km",
    opcion2: "1,500,000 km",
    opcion3: "150,000,000 km",
    opcion4: "15,000,000 km",
    respuestaCorrecta: "150,000,000 km",
  },
  {
    id: 30,
    pregunta: "¿Qué océano baña las costas de California?",
    opcion1: "Atlántico",
    opcion2: "Pacífico",
    opcion3: "Índico",
    opcion4: "Ártico",
    respuestaCorrecta: "Pacífico",
  },
  {
    id: 31,
    pregunta: "¿Qué instrumento se utiliza para medir la presión atmosférica?",
    opcion1: "Termómetro",
    opcion2: "Barómetro",
    opcion3: "Anemómetro",
    opcion4: "Higrómetro",
    respuestaCorrecta: "Barómetro",
  },
  {
    id: 32,
    pregunta:
      "¿Qué planeta del sistema solar tiene un día más largo que un año?",
    opcion1: "Mercurio",
    opcion2: "Venus",
    opcion3: "Marte",
    opcion4: "Júpiter",
    respuestaCorrecta: "Venus",
  },
  {
    id: 33,
    pregunta: "¿En qué país se encuentra la Torre Eiffel?",
    opcion1: "Italia",
    opcion2: "España",
    opcion3: "Francia",
    opcion4: "Reino Unido",
    respuestaCorrecta: "Francia",
  },
  {
    id: 34,
    pregunta: "¿Qué pintor es famoso por su obra 'La Noche Estrellada'?",
    opcion1: "Claude Monet",
    opcion2: "Vincent van Gogh",
    opcion3: "Pablo Picasso",
    opcion4: "Salvador Dalí",
    respuestaCorrecta: "Vincent van Gogh",
  },
  {
    id: 35,
    pregunta: "¿Cuál es el sistema operativo más utilizado en el mundo?",
    opcion1: "Linux",
    opcion2: "macOS",
    opcion3: "Windows",
    opcion4: "Android",
    respuestaCorrecta: "Windows",
  },
  {
    id: 36,
    pregunta: "¿Qué país es conocido como la 'Tierra del Sol Naciente'?",
    opcion1: "Corea del Sur",
    opcion2: "China",
    opcion3: "Japón",
    opcion4: "Tailandia",
    respuestaCorrecta: "Japón",
  },
  {
    id: 37,
    pregunta: "¿Cuál es el nombre del satélite natural de la Tierra?",
    opcion1: "Luna",
    opcion2: "Europa",
    opcion3: "Titán",
    opcion4: "Io",
    respuestaCorrecta: "Luna",
  },
  {
    id: 38,
    pregunta: "¿Qué tipo de animal es la ballena?",
    opcion1: "Pez",
    opcion2: "Ave",
    opcion3: "Mamífero",
    opcion4: "Reptil",
    respuestaCorrecta: "Mamífero",
  },
  {
    id: 39,
    pregunta: "¿Qué país tiene la mayor cantidad de habitantes del mundo?",
    opcion1: "India",
    opcion2: "Estados Unidos",
    opcion3: "China",
    opcion4: "Rusia",
    respuestaCorrecta: "China",
  },
  {
    id: 40,
    pregunta: "¿Qué es el Bosón de Higgs?",
    opcion1: "Una partícula subatómica",
    opcion2: "Un tipo de estrella",
    opcion3: "Una galaxia",
    opcion4: "Una teoría matemática",
    respuestaCorrecta: "Una partícula subatómica",
  },
  {
    id: 41,
    pregunta:
      "¿En qué año se fundó la Organización de las Naciones Unidas (ONU)?",
    opcion1: "1945",
    opcion2: "1939",
    opcion3: "1950",
    opcion4: "1960",
    respuestaCorrecta: "1945",
  },
  {
    id: 42,
    pregunta: "¿Qué país se encuentra en dos continentes?",
    opcion1: "Egipto",
    opcion2: "Turquía",
    opcion3: "Australia",
    opcion4: "Brasil",
    respuestaCorrecta: "Turquía",
  },
  {
    id: 43,
    pregunta: "¿Cuál es la montaña más alta del mundo?",
    opcion1: "Monte Everest",
    opcion2: "K2",
    opcion3: "Kangchenjunga",
    opcion4: "Monte McKinley",
    respuestaCorrecta: "Monte Everest",
  },
  {
    id: 44,
    pregunta: "¿Qué es un año luz?",
    opcion1:
      "El tiempo que tarda la Tierra en dar una vuelta alrededor del Sol",
    opcion2: "La distancia que recorre la luz en un año",
    opcion3: "Una medida de tiempo",
    opcion4: "Una estrella",
    respuestaCorrecta: "La distancia que recorre la luz en un año",
  },
  {
    id: 45,
    pregunta: "¿Qué país inventó el papel?",
    opcion1: "Grecia",
    opcion2: "India",
    opcion3: "Egipto",
    opcion4: "China",
    respuestaCorrecta: "China",
  },
  {
    id: 46,
    pregunta: "¿Cuál es la capital de Canadá?",
    opcion1: "Toronto",
    opcion2: "Montreal",
    opcion3: "Vancouver",
    opcion4: "Ottawa",
    respuestaCorrecta: "Ottawa",
  },
  {
    id: 47,
    pregunta: "¿Qué metal es conocido como el 'metal de transición'?",
    opcion1: "Hierro",
    opcion2: "Cobre",
    opcion3: "Zinc",
    opcion4: "Titanio",
    respuestaCorrecta: "Titanio",
  },
  {
    id: 48,
    pregunta: "¿En qué año se lanzó el primer iPhone?",
    opcion1: "2005",
    opcion2: "2006",
    opcion3: "2007",
    opcion4: "2008",
    respuestaCorrecta: "2007",
  },
  {
    id: 49,
    pregunta: "¿Cuál es el país más pequeño del mundo?",
    opcion1: "Monaco",
    opcion2: "Nauru",
    opcion3: "San Marino",
    opcion4: "Ciudad del Vaticano",
    respuestaCorrecta: "Ciudad del Vaticano",
  },
  {
    id: 50,
    pregunta: "¿Qué científico propuso la teoría de la relatividad?",
    opcion1: "Isaac Newton",
    opcion2: "Galileo Galilei",
    opcion3: "Albert Einstein",
    opcion4: "Nikola Tesla",
    respuestaCorrecta: "Albert Einstein",
  },
];
